# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import mindtrip.origami.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('photo1', models.ImageField(upload_to=mindtrip.origami.models.photo_upload_to, verbose_name='Zdj\u0119cie 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to=mindtrip.origami.models.photo_upload_to, verbose_name='Zdj\u0119cie 2')),
                ('diagram_url', models.URLField(blank=True, null=True, verbose_name='Adres diagramu')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Adres video')),
            ],
            options={'verbose_name': 'Origami', 'verbose_name_plural': 'Origami'},
        ),
    ]
