# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-25 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origami', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='diagram_file',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Plik diagramu'),
        ),
    ]
