# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Opis')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='Wskaz\xf3wki')),
            ],
            options={
                'verbose_name': 'Dzie\u0144',
                'verbose_name_plural': 'Dni',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nazwa')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255, verbose_name='Cel podr\xf3\u017cy')),
                ('summary', models.TextField(verbose_name='Podsumowanie')),
                ('start_at', models.DateField(verbose_name='Data pocz\u0105tku')),
                ('end_at', models.DateField(verbose_name='Data ko\u0144ca')),
                ('hotel', models.CharField(max_length=500, verbose_name='Noclegi')),
                ('hotel_price', models.CharField(max_length=255, verbose_name='Cena nocleg\xf3w')),
                ('travel', models.CharField(max_length=500, verbose_name='Dojazd')),
                ('travel_price', models.CharField(max_length=255, verbose_name='Cena nocleg\xf3w')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='Wskaz\xf3wki')),
                ('tags', models.ManyToManyField(to='trips.Tag', verbose_name='Tagi')),
            ],
            options={
                'verbose_name': 'Wycieczka',
                'verbose_name_plural': 'Wycieczki',
            },
        ),
        migrations.AddField(
            model_name='day',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.Trip', verbose_name='Wycieczka'),
        ),
    ]
