# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nazwa')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kraj',
                'verbose_name_plural': 'Kraje',
            },
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_price',
            field=models.CharField(max_length=255, verbose_name='Cena dojazdu'),
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trips.Country', verbose_name='Kraj'),
            preserve_default=False,
        ),
    ]
