# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20161230_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='trips.Tag', verbose_name='Tagi'),
        ),
    ]
