# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 23:34

from django.db import migrations, models
import mindtrip.trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20161231_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=mindtrip.trips.models.upload_to),
        ),
    ]
