# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mindtrip.trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_views_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=mindtrip.trips.models.photo_upload_to, verbose_name='Zdj\u0119cie')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Opis')),
                ('trip_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.Day', verbose_name='Dzie\u0144 wycieczki')),
            ],
            options={
                'verbose_name': 'Zdj\u0119cie',
                'verbose_name_plural': 'Zdj\u0119cia',
            },
        ),
    ]
