# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tyty\u0142')),
                ('text', models.TextField(verbose_name='Tekst')),
                ('created_at', models.DateField(verbose_name='Data wpisu')),
            ],
            options={
                'verbose_name': 'Wpis',
                'verbose_name_plural': 'Wpisy',
            },
        ),
    ]
