# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='guidebook',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Przewodniki/mapy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_at',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Planowana w'),
        ),
    ]
