# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-08 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_auto_20180618_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='describe_capitol',
            new_name='describe_capital',
        ),
    ]
