# Generated by Django 3.0.3 on 2020-06-10 20:21

import annoying.fields
from django.db import migrations
import json


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_auto_20200206_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='photos_json',
            field=annoying.fields.JSONField(blank=True, deserializer=json.loads, null=True, serializer=annoying.fields.dumps),
        ),
    ]
